### ISSUE TITLE
Add pulseaudio/pipewire support

### ISSUE THREAD

**Issue by seppeel** [rhasspy/wyoming-satellite#32]
Hey,

i keep running the [homeassistant-satellite](https://github.com/synesthesiam/homeassistant-satellite) because of the pulseaudio support (snapcast must run alongside the satellite).

I would love to see pulseaudio support here, too.

Is it possible to adapt the [PR](https://github.com/synesthesiam/homeassistant-satellite/pull/3) in the homeassistant-satellite repository to add pulseaudio (and pipewire) support here?

Or are there better solutions to run snapcast and the wyoming satellite at the same time?

Thanks for your work,
seppel

**Comment by snootched** [comment]
What are you looking for exactly?  This currently runs quite nicely on a few satellites here.
I've set them up as multi-function satellites based on PA.  Including snapcast client, libespot, shairport, and mopidy/mpd/upmpdcli.  Pretty much any device can connect to these.

Even the audio ducking works with a 'hack' of issuing a silence stream then killing it later.
Just use paplay/parecord for your audio commands.
Let me know if you need to see some example scripts on setting this up, happy to share.

**Comment by seppeel** [comment]
Hey, 
I only checked If there are options to use PA like in the HA satellite but didn't notice the difference that we use sound/mic commands instead of devices here.

I would like to see your solution for ducking If you don't mind.

Thanks for your help and sorry for opening an unneccessary issue.

seppel

**Comment by snootched** [comment]
Sure here's some rudimentary options I've played with this week.  That PR looked nice though.
For your media players, generally role=music is the default, but you may need to set this depending on your players.  These streams would be ducked automatically.

Added module for ducking in `/etc/pulse/default.pa`  The `any_role` will duck anything not in the triggers.
`load-module module-role-ducking trigger_roles=announce,phone,notification,event ducking_roles=any_role volume=33%`

Satellite:
`ExecStart=/home/pi/wyoming-satellite/script/run --name 'my cool name' --area 'living room'  --uri 'tcp://0.0.0.0:10700' --wake-uri 'tcp://127.0.0.1:10400' --mic-command 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw' --snd-command 'paplay --property=media.role=announce --rate=16000 --channels=1 --format=s16le --raw' --snd-command-rate 16000  --startup-command 'paplay sounds/power_up4.wav' --detection-command './awake.sh' --tts-stop-command './done.sh'  --wake-word-name 'computer' --mic-noise-suppression 2 --mic-auto-gain 3 --debug`

For now, custom scripts `awake.sh` and `done.sh` used.  Will look into event uri further at some point.
Since parecord media.role property doesn't actually do anything (ie. it won't trigger the ducking) - I worked around this by starting up a pacat stream which plays silence at volume zero and with a role that will cause the ducking to trigger.
It has a client name of `silence` so it can be found later, but I'm sure there's more elegant ways of doing this.

awake.sh
```
#!/bin/bash
echo $(date) [awake.sh] ...Starting awake.sh script
echo $(date) [awake.sh] ...Starting silence
pacat --client-name=silence --volume=0 --property=media.role=notification < /dev/zero & 

echo $(date) [awake.sh] ...Playing stt start beep
paplay --property=media.role=notification sounds/computerbeep_50.wav
```


done.sh
```
#!/bin/bash
echo $(date) [done.sh] ...Starting done.sh script
export PULSE_RUNTIME_PATH=/var/run/user/1000/pulse
sleep 0.5
echo $(date) [done.sh] ...Playing finish beep
paplay --property=media.role=notification sounds/computerbeep_51.wav 

echo $(date) [done.sh] ...Killing 'silence' pulseaudio client
pacmd list-clients | awk '($1 == "index:") {i=$2} ($1 == "application.name" && tolower($0) ~ /silence/) {print i}' | xargs -n1 pacmd kill-client > /dev/null 2>&1
```

**Comment by snootched** [comment]
> @snootched a couple of basic questions:
> 
> 1. If I'm using ubuntu server, am I correct in thinking that given that I'm using ubuntu server this will work better if I use parecord /paplay instead of arecord/aplay?
> 2. When using arecord/aplay I specify the device with -D plughw:CARD=S330,DEV=0. Is there an equivalent with parecord /paplay ?

Hi @ignacio82 - I'm not sure how ubuntu server has packed up pulseaudio, it may set up your defaults correctly on install.
Essentially, aplay (ALSA) is direct hardware access, and pulseaudio is an audio server (which uses ALSA underneath for the hardware access.)

paplay/parecord allow you to do some thinks like the audio ducking etc.  I just find this easier (plus I like accessing it over IP)

There are probably some good general guides on setting up PA that you could look at to get you going.  There a concept of -D with paplay, but it refers to sinks/sources that have been configured in the pulseadio server.

I find that the archlinux documtation on pulseaudio is very very good to get an idea of how things work.

**Comment by ignacio82** [comment]
@snootched any chance you know how to fix this?

```
journalctl -u wyoming-satellite.service -f
Jan 10 03:53:39 mini-server run[58758]: WARNING:root:Mic service disconnected
Jan 10 03:53:42 mini-server run[286738]: Connection failure: Connection refused
```

![image](https://github.com/rhasspy/wyoming-satellite/assets/1833309/7592e3c3-4be2-41a4-83bc-c269c6cc7b14)

![image](https://github.com/rhasspy/wyoming-satellite/assets/1833309/a8956a9d-eb36-4a6f-80fc-2bf19ef84d8e)

![image](https://github.com/rhasspy/wyoming-satellite/assets/1833309/4f356024-a017-4280-8924-ee24d506ab28)


```
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/home/ignacio/wyoming-satellite/script/run --name 'mini-server' \
--uri 'tcp://0.0.0.0:10700' \
--mic-command 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw' \
--snd-command 'paplay --property=media.role=announce --rate=16000 --channels=1 --format=s16le --raw' \
--done-wav /home/ignacio/wav/done.wav \
--awake-wav /home/ignacio/wav/awake.wav \
--vad --mic-auto-gain 5 --mic-noise-suppression 2
WorkingDirectory=/home/ignacio/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```

**Comment by FutureProofHomes** [comment]
Same issue as @ignacio82 here as well.  
![image](https://github.com/rhasspy/wyoming-satellite/assets/155350996/b339921e-e5c7-4ca0-be4c-2b1849600443)

**Comment by FutureProofHomes** [comment]
Using ReSpeaker 2-mic Pi hat, I got things working with this command:
