### ISSUE TITLE
alsa-utils missing in Docker image

### ISSUE THREAD

**Issue by mrichar1** [rhasspy/wyoming-satellite#84]
`alsa-utils` package isn't installed in `python:3.11-slim-bookworm` by default, so the example docs using `aplay` and `arecord` fail.

Fix is to add `alsa-utils` to the `apt-get` command in the Dockerfile. (Happy to make a PR but wasn't sure if this was deliberate since this is only one of a number of audio commands that *could* be used).

**Comment by maxemoose** [comment]
I think those audio commands are intended for use with native installations on a host, not with Docker containers which should use "--snd-uri" & "--mic-uri" instead since the playback and microphone containers are "remote". An example of this can be seen in the [docker-compose.yml](https://github.com/rhasspy/wyoming-satellite/blob/master/docker-compose.yml).

`alsa-utils` is included in the [playback](https://github.com/rhasspy/wyoming-snd-external/blob/master/Dockerfile) and [microphone](https://github.com/rhasspy/wyoming-mic-external/blob/master/Dockerfile) Dockerfiles so it does not strictly _need_ to be included in the base satellite Docker image. In fact, as I learned the hard way, adding it and using that container can lead to [some unpredictable behaviour](https://github.com/rhasspy/wyoming-satellite/issues/35).

Until the Docker containers are actually being published to Docker hub, I'd suggest building and using images from those repos instead of trying to bundle everything into one container.

**Comment by mrichar1** [comment]
Thanks - I'm not sure how I missed the `wyoming-snd-external` and `wyoming-mic-external` projects!

I've now tried running these alongside wyoming-satellite, adding the `/dev/snd` device to both of them, but I get 'device or resource busy' running arecord/aplay on whichever container starts second.

I see from your linked issue that you had success running with 4 containers - is this on a single server? If so did you have to do anything special to share the sound device?

**Comment by maxemoose** [comment]
That's right: 4 containers on a single Raspberry Pi 4 server.

I ran `arecord -L` on the host to find a value for `plughw` to replace `sysdefault` for the `wyoming-mic-external` container. It looks like this for me: `plughw:CARD=Snowball,DEV=0`.

Then I also ran `aplay -L` on the host to find a value for `plughw` to replace `sysdefault` for the `wyoming-snd-external` container.

No other fancy configuration steps were required.

I do find that the `wyoming-mic-external` container seems to lose access the microphone every time I reboot the `wyoming-satellite` container. A simple reboot of the `wyoming-mic-external` container solves the problem.
